In [4]:
import numpy as np
from tqdm import tqdm

# Numpy

행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리

references: 
- [numpy](https://numpy.org/doc/stable/reference/index.html#reference)
- [cs231 numpy](https://cs231n.github.io/python-numpy-tutorial/)
- [Python For Data Science Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

<br>

numpy 특징 <br>
- 파이썬 리스트에 비해 빠르고, 메모리 효율적
- 반복문 없이 배열에 대한 처리 지원
- 다양한 기능 제공
<br>
<br>

numpy 기능 <br>
- 1. shape: numpy dimension
- 2. ndim: shape에서 얼마나 나오는지
- 3. dtype: numpy 원소의 데이터 타입

In [1]:
[item+1 for item in [1, 2, 3, 4, 5]]

[2, 3, 4, 5, 6]

In [2]:
[1, 2, 3, 4, 5] + 1

TypeError: can only concatenate list (not "int") to list

## 배열 생성

### 기본 배열 생성

In [6]:
[1, 2, 3, 4, 5]

[1, 2, 3, 4, 5]

In [10]:
np.array([1, 2, 3, 4, 5]) + 1 # np.array([1, 2, 3, 4, 5]) + np.array([1, 1, 1, 1, 1])

array([2, 3, 4, 5, 6])

In [23]:
np.array([1, 2, 3, 4]) + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (1,4) (1,2) 

In [17]:
a = np.array([
    [[1, 2],
     [1, 2],
     [1, 2],
     [1, 2]],
    [[1, 2],
     [1, 2],
     [1, 2],
     [1, 2]],
     ])

In [19]:
a.shape

(2, 4, 2)

In [20]:
a.ndim

3

In [21]:
a.dtype

dtype('int32')

In [22]:
np.array([
    [[1, 2],
     [1, 2],
     [1, 2],
     [1, 2]],
    [[1, 2],
     [1, 2],
     [1, 2],
     [1, 2]],
     ]) + np.array([1, 2])

array([[[2, 4],
        [2, 4],
        [2, 4],
        [2, 4]],

       [[2, 4],
        [2, 4],
        [2, 4],
        [2, 4]]])

In [26]:
%%timeit
[item+1 for item in range(100000)]

4.44 ms ± 93.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [27]:
%%timeit
np.arange(100000)+1

55 μs ± 914 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


#### arange
일정 범위의 배열을 생성 <br>
python의 range와 유사 <br>
단, arange는 실수 사용 가능 <br>

> 주의 <br>
np.arange(-3, 3, 0.5, dtype=int) <br>
array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

<br>

사용법
```python
x = np.arange(0, 10)
x = np.arange(-5, 5, 0.5)
```

In [30]:
range(1, 100, 0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [32]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [33]:
np.arange(1, 10, 0.5, dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### linspace

arange와 유사 <br>
start와 stop를 주어진 숫자 만큼 분할

<br>

사용법
```python
x = np.linspace(2, 3, num=5)
x = np.linspace(2, 3, num=5, endpoint=False)    # 끝 점 미포함 
```

In [35]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
np.linspace(0, 10, num=5, endpoint=False)

array([0., 2., 4., 6., 8.])

#### eye

대각행렬이 1이고 나머지가 0인 행렬 생성 <br>
k를 이용하여 1의 위치를 조정할 수 있음 <br>
<br>

사용법
```python
x = np.eye(10)    # np.identity와 동일
x = np.eye(10, k =1)
```

In [40]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [44]:
np.eye(5, k=-1) + np.eye(5) + np.eye(5, k=1)

array([[1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.]])

#### zeros

shape을 입력하면 모든 값이 0인 해당 shape에 맞는 배열 생성 <br>

사용법
```python
x = np.zeros(5)
x = np.zeros((5, 2), dtype=float)
```

In [45]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.zeros((5, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

#### ones

shape을 입력하면 모든 값이 1인 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.ones(5)
x = np.ones((5, 2), dtype=float)
```

In [49]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [52]:
np.ones((5, 2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

#### full

shape과 숫자를 입력하면 입력한 숫자로 찬 해당 shape에 맞는 배열 생성 <br>
<br>

사용법
```python
x = np.full(5, np.inf)
x = np.full((5, 2), np.nan)
```

In [59]:
np.full((5, 2), 0)  # np.zeros((5, 2))
np.full((5, 2), 1)  # np.ones((5, 2))
np.full((5, 2), np.inf)

array([[inf, inf],
       [inf, inf],
       [inf, inf],
       [inf, inf],
       [inf, inf]])

In [60]:
np.full((5, 2), np.nan)

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])

#### tril

lower triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
```

In [62]:
np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], k=1)

array([[ 1,  2,  0],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### triu

upper triangle matrix 생성 <br>
m값을 이용하여 삼각행렬 이동 가능 <br>
<br>

사용법
```python
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
x = np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)
```

In [63]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

### 랜덤 배열 생성

#### random

균등분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.random(size=(2, 3))    # size: dim
```

In [79]:
np.random.random(size=(2, 3))

array([[0.23106704, 0.97488547, 0.62468254],
       [0.66354021, 0.49946067, 0.89204272]])

#### randint

지정한 범위 내에서 임의의 수 생성

사용법
```python
x = np.random.randint(0, 10, size=(5,2))    # size: dim
```

In [80]:
np.random.randint(0, 10, size=(2, 3))

array([[5, 7, 2],
       [5, 0, 5]])

In [81]:
np.random.randint(1, 46, size=(10000, 6))

array([[14, 10, 34, 11, 26, 16],
       [ 6, 32, 21, 24, 12,  8],
       [17, 17, 24, 20, 14,  1],
       ...,
       [31, 13, 40,  7,  7, 31],
       [41, 15, 44, 25, 32, 42],
       [40, 16, 35, 43, 42, 36]])

#### normal

정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.normal(loc=0, scale=1, size=(2, 3))
# loc: 평균
# scale: 분산
# size: dim
```

In [83]:
np.random.normal(loc=100, scale=20, size=(2, 3))

array([[118.95619217,  79.87068614, 126.17672917],
       [ 90.6389225 ,  93.16624417, 114.9624717 ]])

#### randn

표준정규분포에서 입력한 차원 만큼 데이터 생성 <br>
<br>

사용법
```python
x = np.random.randn(2, 3)
```

In [84]:
np.random.normal(size=(2, 3))

array([[ 0.36928238,  1.15611381, -0.76541012],
       [ 0.8399455 ,  1.253677  , -1.59228336]])

## 배열 조작

### 배열 결합

#### concatenate

두 배열을 결합 <br>
<br>

사용법 
```python
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)
np.concatenate([a, b], axis=0)
np.concatenate([a, b], axis=1)
```

In [91]:
a = np.arange(12).reshape(2, 6)
b = np.arange(12).reshape(2, 6)

In [92]:
np.concatenate([a, b], axis=1)

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11]])

In [93]:
np.concatenate([a, b], axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### 배열 분할

#### array_split

주어진 배열을 분할 <br>
<br>

사용법
```python
x = np.arange(9.0)
np.split(x, 3)
np.split(x, [3, 5, 6, 10])
```

In [98]:
x = np.arange(9)
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [99]:
x = np.arange(9)
np.split(x, [1, 3, 5, 7])

[array([0]), array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

### 차원 변경

#### reshape

배열의 모양을 원하는 형태로 바꿈 <br>
단, 바꾸는 배열의 차원 곱은 원 배열의 차원 곱과 일치해야 함 <br>
<br>

사용법
```python
x = np.arange(30)
x.reshape(5, 6)
```


In [ ]:
np.arange(12).reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

#### flatten

배열을 1차원 배열로 바꿈 <br>
<br>
사용법 <br>
```python
x = np.arange(30).reshape(2, 5, 3)
x.flatten()
```

In [101]:
x = np.arange(12).reshape(2, 2, 3)
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### squeeze

불필요한 차원을 제거 <br>
즉, 길이가 0인 차원을 제거 <br>
<br>

사용법
```python
x = np.arange(10).reshape(10, 1, 1)
x.squeeze()
```

In [104]:
x = np.arange(6).reshape(1, 1, 1, 1, 1, 2, 3)
x.squeeze()

array([[0, 1, 2],
       [3, 4, 5]])

#### expand_dims

차원 추가 <br>
<br>

사용법
```python
x = np.arange(10)
np.expand_dims(x, 0)
```

In [107]:
x = np.arange(10)
print(x.shape)
x1 = np.expand_dims(x, 0)
print(x1.shape)

(10,)
(1, 10)


In [110]:
x[np.newaxis]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

### 모양 변경

##### roll

배열을 입력한 수 만큼 이동 <br>
<br>

사용법
```python
x = np.arange(10)
np.roll(x, 2)
```

```python
x = np.reshape(x, (2, 5))
np.roll(x, 1)
np.roll(x, -1, axis=0)
np.roll(x, -1, axis=1)
```

In [117]:
x = np.arange(5)
print(x)
print(np.roll(x, shift=1))
print(np.roll(x, shift=-1))
print(np.roll(x, shift=2))

[0 1 2 3 4]
[4 0 1 2 3]
[1 2 3 4 0]
[3 4 0 1 2]


In [122]:
a = ['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01', '2024-05-01']
b = np.roll(a, shift=-1)
print(a)
print(b)
list(zip(a, b))[:-1]

['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01', '2024-05-01']
['2024-02-01' '2024-03-01' '2024-04-01' '2024-05-01' '2024-01-01']


[('2024-01-01', '2024-02-01'),
 ('2024-02-01', '2024-03-01'),
 ('2024-03-01', '2024-04-01'),
 ('2024-04-01', '2024-05-01')]

##### flip

지정된 축을 기준으로 배열을 뒤집음 <br>
<br>

사용법

```python
x = np.arange(10).reshape(5, 2)
np.flip(x, 0)
```


In [128]:
x = np.arange(10).reshape(5, 2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [130]:
np.flip(x, axis=0)

array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

In [131]:
np.flip(x, axis=1)

array([[1, 0],
       [3, 2],
       [5, 4],
       [7, 6],
       [9, 8]])

### 축 변경

#### swapaxes

두 축의 위치를 지정하여 변경 <br>
<br>

사용법
```python
x = np.arange(100).reshape(5, 2, 10)
x.swapaxis(0, 2)    # 0 <-> 2
```

In [134]:
x = np.arange(100).reshape(5, 2, 10)    # (batch_size, seq_len, dim)
x.swapaxes(2, 1).shape                  # (batch_size, dim, seq_len)

(5, 10, 2)

#### transpose

여러 축의 위치를 변경 <br>
transpose에 들어가는 인자는 축의 순서 <br>
<br>

사용법

```python
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1)    # 1번 축과 2번 축을 바꿈
x.transpose(2, 0, 1)    # 2->0, 0->1, 1->2
```

In [135]:
x = np.arange(100).reshape(5, 2, 10)        # (batch_size, seq_len, dim)
x.transpose(0, 2, 1).shape                  # (batch_size, dim, seq_len)

(5, 10, 2)

### 배열 정렬

#### sort

주어진 축을 기준으로 배열 정렬 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.sort(axis=1)
x
```



In [142]:
x = np.random.randint(0, 10, size=(5, 2))
x

array([[5, 1],
       [6, 8],
       [7, 0],
       [9, 1],
       [0, 0]])

In [143]:
x.sort(axis=0)
x

array([[0, 0],
       [5, 0],
       [6, 1],
       [7, 1],
       [9, 8]])

In [144]:
x.sort(axis=1)
x

array([[0, 0],
       [0, 5],
       [1, 6],
       [1, 7],
       [8, 9]])

#### argsort

주어진 축을 기준으로 정렬된 배열의 인덱스 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
x.argsort(axis=1)
```


In [148]:
x = np.random.randint(0, 10, 5)
x

array([1, 7, 3, 5, 6])

In [149]:
x.argsort()

array([0, 2, 3, 4, 1], dtype=int64)

### 기타

##### unique

배열 내의 중복값 제거 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, (5, 2))
np.unique(x, axis=0)
```

In [151]:
x = np.random.randint(0, 5, 20)
x

array([1, 2, 3, 4, 0, 0, 2, 0, 4, 0, 4, 2, 2, 1, 2, 0, 2, 0, 3, 0])

In [153]:
np.unique(x)

array([0, 1, 2, 3, 4])

#### nan_to_num

배열 내의 nan 값을 특정 숫자로 변환 <br>
<br>

사용법
```python
x = np.full((3, 4), np.nan)
np.nan_to_num(x, nan=1)


In [155]:
x = np.full((3, 4), np.nan)
np.nan_to_num(x, nan=10)

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

#### trim_zeros

배열 내의 0값을 제거 <br>
<br>

사용법
```python
x = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(x, trim='f')    # 앞의 0만 제거
np.trim_zeros(x, trim='b')    # 뒤의 0만 제거
np.trim_zeros(x, trim='fb')   # 앞뒤 0 제거
```

In [158]:
x = np.array([0, 0, 1, 1, 1, 0, 0])
print(np.trim_zeros(x, trim='f'))
print(np.trim_zeros(x, trim='b'))
print(np.trim_zeros(x, trim='fb'))

[1 1 1 0 0]
[0 0 1 1 1]
[1 1 1]


stride_tricks

배열을 주어진 윈도우 만큼 분할 <br>
<br>

사용법
```python
x = np.arange(10)
y = np.lib.stride_tricks.sliding_window_view(x, 3)
```

In [162]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[x[i:i+4] for i in range(7)]

[[1, 2, 3, 4],
 [2, 3, 4, 5],
 [3, 4, 5, 6],
 [4, 5, 6, 7],
 [5, 6, 7, 8],
 [6, 7, 8, 9],
 [7, 8, 9, 10]]

In [163]:
np.lib.stride_tricks.sliding_window_view(x, 4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

## 배열 탐색

### argmax

축을 기준으로 배열에서 최댓걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmax(x)
np.argmax(x, axis=0)
```

In [169]:
x = np.arange(6).reshape(2, 3)
print(x)
print(np.argmax(x))
print(np.argmax(x, axis=1))
print(np.argmax(x, axis=0))

[[0 1 2]
 [3 4 5]]
5
[2 2]
[1 1 1]


### argmin

축을 기준으로 배열에서 최솟걊의 index 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.argmin(x)
np.argmin(x, axis=0)
```



In [170]:
x = np.arange(6).reshape(2, 3)
print(x)
print(np.argmin(x))
print(np.argmin(x, axis=1))
print(np.argmin(x, axis=0))

[[0 1 2]
 [3 4 5]]
0
[0 0]
[0 0 0]


### where

특정 조건에 맞는 값의 index 반환 또는 값 변환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.where(x < 5)    # 조건을 만족하는 값의 인덱스 반환
np.where(x < 5, 1, 0)    # x가 5보다 작은 값은 1, 그렇지 않으면 0
```

In [176]:
x = np.arange(6, 0, -1)
x

array([6, 5, 4, 3, 2, 1])

In [177]:
np.where(x < 3)[0]

array([4, 5], dtype=int64)

In [178]:
np.where(x < 3, 1, 0)

array([0, 0, 0, 0, 1, 1])

### extract

특정 조건에 맞는 값을 반환 <br>
<br>

사용법
```python
x = np.arange(6).reshape(2,3)
np.extract(x > 2, x)
```

In [179]:
x = np.arange(6, 0, -1)
x

array([6, 5, 4, 3, 2, 1])

In [180]:
np.extract(x < 3, x)

array([2, 1])

##  배열 연산

### matmul

행렬 곱 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))

np.matmul(x, y)
x @ y
```

In [203]:
x = np.random.randint(0, 10, size=(2,2))
y = np.random.randint(0, 10, size=(2,2))
print(x)
print(y)

[[8 1]
 [0 6]]
[[1 6]
 [7 3]]


In [204]:
x*y

array([[ 8,  6],
       [ 0, 18]])

In [205]:
np.matmul(x, y)

array([[15, 51],
       [42, 18]])

In [206]:
x@y

array([[15, 51],
       [42, 18]])

### eigen

eigenvalue, eigenvector 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.eig(x)
```



In [228]:
x = np.random.randint(0, 10, size=(2, 2))
x

array([[2, 0],
       [5, 2]])

In [229]:
np.linalg.eig(x)

EigResult(eigenvalues=array([2., 2.]), eigenvectors=array([[ 0.0000000e+00,  8.8817842e-17],
       [ 1.0000000e+00, -1.0000000e+00]]))

### det

배열의 행렬식을 구함 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.det(x)
```

In [207]:
x = np.random.randint(0, 10, size=(2, 2))
x

array([[5, 4],
       [7, 7]])

In [208]:
np.linalg.det(x)

6.999999999999999

In [209]:
x = np.random.randint(0, 10, size=(4, 4))

In [212]:
np.linalg.det(x)

508.00000000000006

### trace
대각원소의 합 반환 <br>
<br>

사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.trace(x)
```

In [214]:
x = np.random.randint(0, 10, size=(2, 2))
print(x)
print(np.trace(x))

[[5 8]
 [9 7]]
12


### solve

선형 방정식의 해를 반환 <br>
<br>


사용법
```python
#  x_0 + 2*x_1 = 1
# 3x_0 + 5*x_1 = 2:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)
```

In [215]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
np.linalg.solve(a, b)

array([-1.,  1.])

inv

역행렬 <br>
<br>


사용법
```python
x = np.random.randint(0, 10, size=(2,2))
np.linalg.inv(x)
```

In [217]:
x = np.random.randint(0, 10, size=(2,2))
print(x)
print(np.linalg.inv(x))

[[9 4]
 [2 1]]
[[ 1. -4.]
 [-2.  9.]]


## 통계 함수

#### ptp

축별 최댓값 - 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.ptp(axis=0)
```

In [182]:
x = np.random.randint(0, 10, (2, 5))
x

array([[6, 9, 2, 9, 8],
       [1, 7, 4, 2, 8]])

In [183]:
x.ptp(axis=1)

array([7, 7])

In [184]:
x.ptp(axis=0)

array([5, 2, 2, 7, 0])

#### median

축별 중앙값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
np.median(x, axis=0)
```

In [185]:
x = np.random.randint(0, 10, (2, 5))
x

array([[2, 5, 4, 5, 1],
       [1, 6, 4, 3, 2]])

In [186]:
np.median(x, axis=1)

array([4., 3.])

### sum

축별 합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
x.sum(axis=1)
```

In [188]:
x = np.random.randint(0, 10, (2, 5))
x

array([[1, 3, 5, 5, 5],
       [4, 4, 0, 0, 2]])

In [189]:
x.sum(axis=1)

array([19, 10])

In [190]:
x.sum(axis=0)

array([5, 7, 5, 5, 7])

### average

축별 가중합 산출 <br>
<br>

사용법
```python
x = np.array([3, 4, 5])
np.average(x, weights=[0.5, 0.3, 0.2])
```

In [200]:
x= np.array([3, 4, 5])
np.average(x, weights=[20, 10, 10])

3.75

In [ ]:
4.5, 3.5, 3, 4, 4, 2.5 # 2, 3, 3, 2, 3, 3

In [201]:
np.average([4.5, 3.5, 3, 4, 4, 2.5], weights=[2, 3, 3, 2, 3, 3])

3.5

### mean

축별 평균 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.mean(axis=1)
```

In [198]:
x = np.arange(12).reshape(4,3)
x.mean(axis=0)

array([4.5, 5.5, 6.5])

### min

축별 최솟값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.min(axis=1)
```

In [191]:
x = np.arange(12).reshape(4,3)
x.min(axis=1)

array([0, 3, 6, 9])

### max

축별 최댓값 산출 <br>
<br>

사용법
```python
x = np.arange(12).reshape(4,3)
x.max(axis=1)
```

In [192]:
x = np.arange(12).reshape(4,3)
x.max(axis=1)

array([ 2,  5,  8, 11])

### std
축별 표준편차 산출 <br>
<br>

사용법

```python
x = np.arange(12).reshape(4,3)
x.std(axis=1)
```

In [194]:
x = np.arange(12).reshape(2, 6)
x.std(axis=1)

array([1.70782513, 1.70782513])

### cov

공분산 산출 <br>
<br>

사용법
```python
x = np.random.rand(25).reshape(5, 5)
np.cov(x)
```

In [195]:
x = np.random.rand(25).reshape(5, 5)
np.cov(x)

array([[ 0.02160042, -0.0022751 , -0.01104707,  0.02341812, -0.01539199],
       [-0.0022751 ,  0.0816557 ,  0.02253073,  0.02661483,  0.00896177],
       [-0.01104707,  0.02253073,  0.03871297, -0.03365429, -0.01777004],
       [ 0.02341812,  0.02661483, -0.03365429,  0.08797811, -0.00691876],
       [-0.01539199,  0.00896177, -0.01777004, -0.00691876,  0.06305733]])

In [196]:
x = np.random.rand(25).reshape(5, 5)
np.corrcoef(x)

array([[ 1.        ,  0.07346029, -0.31305498, -0.95820256,  0.01123071],
       [ 0.07346029,  1.        , -0.25718608,  0.1522279 ,  0.61914329],
       [-0.31305498, -0.25718608,  1.        ,  0.09307667, -0.35438623],
       [-0.95820256,  0.1522279 ,  0.09307667,  1.        ,  0.11845826],
       [ 0.01123071,  0.61914329, -0.35438623,  0.11845826,  1.        ]])

# Practice

In [233]:
# 반 학생의 성적 순서가 1~100까지 있다.
#  1 ~  20: 1
# 21 ~  40: 2
# 41 ~  60: 3
# 61 ~  80: 4
# 81 ~ 100: 5
# for문을 사용하지 않고 각 숫자를 부여할 수 있는 코드 작성
np.arange(1, 101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])